name: 'Install Python dependencies'
runs:
  using: "composite"
  steps:
    - name: update pip
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
      shell: bash
    - name: get pip cache dir
      id: pip-cache
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      shell: bash
    - name: cache pip
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - run: pip install -r requirements.txt
      shell: bash
